### ISSUE TITLE
ERROR: Failed to assume domain-protect-audit role in AWS account 

### ISSUE THREAD

**Issue by ammarion** [ovotech/domain-protect#13]
For some reason all lambdas can't assume the role I did create this role in all accounts and I am assuming the lambdas would construct this dynamically after assuming role into the org account and getting all accounts ID -- Does this solution assume that we deploy the solution in the org account or security account? 

```
[ERROR]	2021-07-08T18:28:07.025Z	ce12dc73-4302-453b-adc3-b3fbc9ab3eeb	ERROR: Failed to assume domain-protect-audit role in AWS account 
Traceback (most recent call last):
  File "/var/task/alias-eb.py", line 25, in assume_role
    assumed_role_object = stsclient.assume_role(RoleArn = security_audit_role_arn, RoleSessionName = project)
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::12345678910:assumed-role/domain-protect-lambda-default/domain-protect-alias-eb-default is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam:::role/domain-protect-audit
```

**Comment by ammarion** [comment]
I needed to update the variables file. I am still getting error but the role arn is fixed

**Comment by paulschwarzenberger** [comment]
https://github.com/ovotech/domain-protect/pull/15 
Provides examples of assume role policies
