### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ammarion** [ovotech/domain-protect#14]
The lambdas seems to indicate that it assumed role into the org account even if there is access denied error.

For example, I forgot to add the org account ID to terrafrom variables and the logs showed that the lambda assumed role. After updating the file with the ID my trust policy wasn't set right so they failed to assume the role but the logs also show that the role was assumed.

```
[ERROR]	2021-07-08T19:33:01.162Z	aa4701c8-0aa1-4a89-9fa7-feae380c7590	ERROR: Failed to assume domain-protect-audit role in AWS account 828414645366
Traceback (most recent call last):
  File "/var/task/cname-eb.py", line 25, in assume_role
    assumed_role_object = stsclient.assume_role(RoleArn = security_audit_role_arn, RoleSessionName = project)
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::yyyyyyyyyyyy:assumed-role/domain-protect-lambda-default/domain-protect-cname-eb-default is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxxxxxx:role/domain-protect-audit
```

**Comment by paulschwarzenberger** [comment]
Thanks for raising this, I've replicated the issue

**Comment by paulschwarzenberger** [comment]
Corrected log message handling: https://github.com/ovotech/domain-protect/pull/18
